### ISSUE TITLE
Remove sentences one doesnt like

### ISSUE THREAD

**Issue by jubalh** [chickendude/Natibo#26] opened 2018-12-24 11:33 UTC
I think the the new Glossika AI one can remove sentences one doesnt like from being displayed.

**Comment by chickendude** [comment] 2019-01-07 06:40
This is definitely planned, i'm thinking more of an ignore feature so you could potentially unignore it as well, however there are a few complicated things like whether it should ignore the sentence for all of that language's courses or just that one.

**Comment by chickendude** [comment] 2019-01-07 06:41
duplic

**Comment by chickendude** [comment] 2019-01-07 06:42
Duplicate of #11.

**Closed by chickendude** 2019-01-07 06:41 UTC
Labels: enhancement, planned
